<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<RevitYear Condition="'$(RevitYear)' == ''">2025</RevitYear>
		<RevitYear Condition="'$(Configuration)' != ''">$(Configuration.Substring($([MSBuild]::Subtract($(Configuration.Length), 4))))</RevitYear>
	</PropertyGroup>

	<PropertyGroup>
		<BuildType Condition="$(Configuration.StartsWith('Debug'))">Debug</BuildType>
		<BuildType Condition="$(Configuration.StartsWith('Release'))">Release</BuildType>
	</PropertyGroup>

	<Target Name="ShowSolutionDir" BeforeTargets="BeforeBuild">
		<Message Text="REVIT YEAR = $(RevitYear)" Importance="High" />
		<Message Text="BUILD TYPE = $(BuildType)" Importance="High" />
	</Target>

	<PropertyGroup>
		<TargetFramework Condition="'$(RevitYear)' == '2025'">net8.0-windows</TargetFramework>
		<TargetFramework Condition="'$(RevitYear)' == '2026'">net8.0-windows</TargetFramework>
		<TargetFramework Condition="'$(RevitYear)' == '2027'">net10.0-windows</TargetFramework>
		<LangVersion>12.0</LangVersion>
		<OutputPath>..\..\build\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Configurations>Debug;Release;Debug2025;Release2025;Release2026;Debug2026;Debug2027;Release2027</Configurations>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<NoWarn>$(NoWarn);MSB3277</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(BuildType)' == 'Debug'">
		<DefineConstants>TRACE;DEBUG;Revit$(RevitYear)</DefineConstants>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<StartAction>Program</StartAction>
		<DebugEngines>{351668CC-8477-4fbf-BFE3-5F1006E4DB1F}</DebugEngines>
		<StartProgram>C:\Program Files\Autodesk\Revit $(RevitYear)\Revit.exe</StartProgram>
		<DebugSymbols>true</DebugSymbols>
		<Optimize>false</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(BuildType)' == 'Release'">
		<DefineConstants>TRACE;Revit$(RevitYear)</DefineConstants>
		<DebugSymbols>false</DebugSymbols>
		<Optimize>true</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="RevitAPIUI">
			<HintPath>$(SolutionDir)references\Revit $(RevitYear)\RevitAPIUI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPI">
			<HintPath>$(SolutionDir)\references\Revit $(RevitYear)\RevitAPI.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>


</Project>
